@base_url=http://127.0.0.1:8000

### Этап 4 Регистрация
POST {{base_url}}/user/register
Content-Type: application/json

{
    "first_name": "ser2",
    "last_name":"ser2",
    "email":"medvedevsm1989@yandex.ru",
    "password":"asd12322",
    "company":"asd",
    "position":"1"
}

### Этап 4 Регистрация не валидная
POST {{base_url}}/user/register
Content-Type: application/json

{
    "first_name": "ser2",
    "last_name":"ser2",
    "email":"medvedevsm1989@yandex.ru",
    "password":"1",
    "company":"asd",
    "position":"1"
}


### Этап 4 Вход
# @name postLogin
POST {{base_url}}/user/login
Content-Type: application/json

{
    "password":"asd12322",
    "email":"medvedevsm1989@yandex.ru"
}

###
@token = {{postLogin.response.body.Token}}

### Этап 4 Невалидный Вход
# @name postLogin
POST {{base_url}}/user/login
Content-Type: application/json

{

}

### Этап 4 получить инфу о себе
GET {{base_url}}/user/details
Content-Type: application/json
Authorization: Token {{token}}

### Этап 4 не авторизованный не может получить инфу о себе
GET {{base_url}}/user/details
Content-Type: application/json

###
### Этап 4 получить инфу о себе
PATCH {{base_url}}/user/details/
Content-Type: application/json
Authorization: Token {{token}}

{
    "first_name": "ser4",
    "password": "asd12322new"
}

### Этап 4 Вход  полсе обновления
# @name postLogin
POST {{base_url}}/user/login
Content-Type: application/json

{
    "password":"asd12322new",
    "email":"medvedevsm1989@yandex.ru"
}


### Этап 4 Вход  полсе обновления
# @name postLogin2
POST {{base_url}}/user/login
Content-Type: application/json

{
    "password":"!QAZ1qaz123",
    "email":"asd2@asd.com"
}

###
@tokenadm = {{postLogin.response.body.Token}}
### Этап 3 заполнение из yaml
POST {{base_url}}/partner/update
Content-Type: application/json
Authorization: Token {{token}}

{
    "url": "https://raw.githubusercontent.com/netology-code/python-final-diplom/master/data/shop1.yaml"
}

### Просмотреть категории
GET {{base_url}}/categories
Content-Type: application/json

### Просмотреть магазинов
GET {{base_url}}/shops
Content-Type: application/json

### Просмотреть products
GET {{base_url}}/products?category_id=1
Content-Type: application/json


### Этап 4 Список товаров
GET {{base_url}}/products
Content-Type: application/json


### Этап 4 Карточка товара ?????????
GET {{base_url}}/products
Content-Type: application/json


### Этап 4 Корзина GET
GET {{base_url}}/basket
Content-Type: application/json
Authorization: Token {{token}}

### Этап 4 Корзина POST
POST {{base_url}}/basket
Content-Type: application/json
Authorization: Token {{token}}

{
    "items": "[{\"product_info\":5,\"quantity\":1,\"shop\":\"Связной\"}]"
}

### Получить контакты
GET {{base_url}}/user/contact
Content-Type: application/json
Authorization: Token {{token}}


### Заполнить контакты 
POST {{base_url}}/user/contact
Content-Type: application/json
Authorization: Token {{token}}

{
    "city":"Moscow",
    "street":"street 1",
    "house":"452",
    "structure":"1",
    "building":"1",
    "apartment":"33",
    "user": 35,
    "phone": "89853662581"
}