@base_url=http://127.0.0.1:8000
@base_url=http://localhost
@products_url=https://raw.githubusercontent.com/netology-code/python-final-diplom/master/data/shop1.yaml

### 1. RegisterAccount
POST {{base_url}}/user/register
Content-Type: application/json

{
    "first_name": "ser2",
    "last_name":"ser2",
    "email":"medvedevsm1989@yandex.ru",
    "password":"asd12322",
    "company":"asd",
    "position":"1"
}

### 1. RegisterAccount (не валидная)
POST {{base_url}}/user/register
Content-Type: application/json

{
    "first_name": "ser2",
    "last_name":"ser2",
    "email":"medvedevsm1989@yandex.ru",
    "password":"1",
    "company":"asd",
    "position":"1"
}


### 2. LoginAccount
# @name postLogin
POST {{base_url}}/user/login
Content-Type: application/json

{
    "password":"asd12322",
    "email":"medvedevsm1989@yandex.ru"
}

###
@token = {{postLogin.response.body.Token}}

### 2. LoginAccount (не валидный)
# @name postLogin
POST {{base_url}}/user/login
Content-Type: application/json

{

}

### 3. AccountDetails
GET {{base_url}}/user/details
Content-Type: application/json
Authorization: Token {{token}}

### 3. AccountDetails (не валидный)
GET {{base_url}}/user/details
Content-Type: application/json

### 3. AccountDetails
PATCH {{base_url}}/user/details/
Content-Type: application/json
Authorization: Token {{token}}

{
    "first_name": "ser4",
    "password": "asd12322new"
}

### 3. LoginAccount after change AccountDetails
# @name postLogin2
POST {{base_url}}/user/login
Content-Type: application/json

{
    "password":"!QAZ1qaz123",
    "email":"asd2@asd.com"
}

###
@tokenadm = {{postLogin.response.body.Token}}

### 4. PartnerUpdate
POST {{base_url}}/partner/update
Content-Type: application/json
Authorization: Token {{token}}

{
    "url": "{{products_url}}"
}

### 5. CategoryView
GET {{base_url}}/categories
Content-Type: application/json

### 6. ShopView
GET {{base_url}}/shops
Content-Type: application/json

### 7. ProductInfoView
GET {{base_url}}/products?category_id=1
Content-Type: application/json


### 7. ProductInfoView
GET {{base_url}}/products
Content-Type: application/json

### 8. ContactView
GET {{base_url}}/user/contact/
Content-Type: application/json
Authorization: Token {{token}}

### 8. ContactView
POST {{base_url}}/user/contact/
Content-Type: application/json
Authorization: Token {{token}}

{
    "city":"Moscow",
    "street":"street 1",
    "house":"452",
    "structure":"1",
    "building":"1",
    "apartment":"33",
    "phone": "88005553555"
}

### 8. ContactView
PATCH  {{base_url}}/user/contact/36/
Content-Type: application/json
Authorization: Token {{token}}

{
    "city":"zzz2",
    "street":"street 1",
    "house":"452",
    "structure":"1",
    "building":"1",
    "apartment":"33",
    "phone": "88005553555"
}

### 8. ContactView
DELETE  {{base_url}}/user/contact/36/
Content-Type: application/json
Authorization: Token {{token}}

### 9. PartnerState
GET {{base_url}}/partner/state
Content-Type: application/json
Authorization: Token {{token}}

### 9. PartnerState
POST {{base_url}}/partner/state
Content-Type: application/json
Authorization: Token {{token}}

{
    "state": true
}

### 10. BasketView
GET {{base_url}}/basket
Content-Type: application/json
Authorization: Token {{token}}

### 10. BasketView
POST {{base_url}}/basket
Content-Type: application/json
Authorization: Token {{token}}


[{"product_info":11,"quantity": 1},{"product_info":12,"quantity": 1}]


### 10. BasketView
POST {{base_url}}/basket
Content-Type: application/json
Authorization: Token {{token}}


[{"product_info":"45fghfghfg","quantity": 1}]


### 10. BasketView
DELETE {{base_url}}/basket
Content-Type: application/json
Authorization: Token {{token}}

{
    "ordered_items": [101, 100]
}

### 10. BasketView
PUT {{base_url}}/basket
Content-Type: application/json
Authorization: Token {{token}}

[{"id":100,"quantity":1}]


### 11. PartnerOrders
GET {{base_url}}/partner/orders
Content-Type: application/json
Authorization: Token {{token}}

### 12. OrderView

GET {{base_url}}/order
Content-Type: application/json
Authorization: Token {{token}}

### 12. OrderView

POST {{base_url}}/order
Content-Type: application/json
Authorization: Token {{token}}

{
    "contact": 37
}







###
POST http://localhost/user/login
Content-Type: application/json

{
    "password":"admin7712345",
    "email":"admin77@admin.com"
}

@token=6f7c10f769689097ef81e1702754c46c75b828ac

###
POST http://localhost/partner/update
Content-Type: application/json
Authorization: Token {{token}}

{
    "url": "https://raw.githubusercontent.com/netology-code/python-final-diplom/master/data/shop1.yaml"
}
###

POST http://localhost/user/register
Content-Type: application/json

{
    "first_name": "ser2",
    "last_name":"ser2",
    "email":"medvedevsm1989@yandex.ru",
    "password":"asd12322",
    "company":"asd",
    "position":"1"
}

###
POST http://localhost/user/login
Content-Type: application/json

{
    "password":"asd12322",
    "email":"medvedevsm1989@yandex.ru"
}
###
@token = a29edd5df839b0f242c1352e2a1d13a8266d78c5